version: '3'

services: 

    postgres:
        image: postgres:10-alpine
        env_file: .env
        ports:
            - 5500:5432
        volumes:
            - ./data:/var/lib/postgresql/data
        networks:
            - default

networks:
    default:
        driver: bridge