# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: test
on: [push]
jobs:
  check-flake_isort:
   runs-on: ubuntu-latest
   strategy:
     matrix:
       python-version: [3.6]
   steps:
    - run: python -V
    - run: apt install -y gcc git openssh postgresql-dev musl-dev bash libxslt-dev libxml2-dev make
    - run: pip install -r requirements-dev.txt
    - run: make pep8

