# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

image: python:3.6.8-alpine

stages:
  - test

test:
  script:
    - python -V
    - apk add --no-cache --update gcc git openssh postgresql-dev musl-dev bash libxslt-dev libxml2-dev make
    - pip install -r requirements-dev.txt
    - make pep8

